language: go
sudo: false
go:
  - tip
env:
  - PROJECT=replacer
before_install:
  - go get github.com/mattn/goveralls
install:
  - go get -t -v ./$PROJECT/...
before_script:
  - cd $PROJECT
script:
  - $HOME/gopath/bin/goveralls -service travis-ci